### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by tyh97** [bamsumit/slayerPytorch#16]
An error occurred while I was testing the program of test and example。

The following error occurs in the file nminstCNN.py

> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=313 error=209 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "/home/tyh/PycharmProjects/DeepLearning/practice/slayerPytorch-master/example/03_NMNIST_CNN/nmnistCNN.py", line 128, in <module>
    stats.training.correctSamples += torch.sum(snn.predict.getClass(output) == label).data.item()
  File "/usr/local/lib/python3.6/dist-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/spikeClassifier.py", line 19, in getClass
    numSpikes = torch.sum(spike, 4, keepdim=True).cpu()
RuntimeError: CUDA error: no kernel image is available for execution on the device

The following error occurs in the test case

> ERROR:`  test_slayerLoihi001 (unittest.loader._FailedTest)
ImportError: Failed to import test module: test_slayerLoihi001
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/tyh/PycharmProjects/DeepLearning/practice/slayerPytorch-master/test/test_slayerLoihi001.py", line 74, in <module>
    spikeHid, uHid = slayer.spikeLoihiFull(wSpikeIn)[0:2]
  File "/usr/local/lib/python3.6/dist-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayerLoihi.py", line 122, in spikeLoihiFull
    return _spike.loihi(weightedSpikes, self.neuron, self.simulation['Ts'])
  File "/usr/local/lib/python3.6/dist-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayerLoihi.py", line 225, in loihi
    return spike/Ts, voltage, current
RuntimeError: CUDA error: no kernel image is available for execution on the device
Ran 20 tests in 3.739s
FAILED (errors=13)

### Environment
-----------------------------------------------------

> platform              linux
system                    ubuntu18.04
PyTorch                   1.4.0
numpy                     1.18.1
cuda                         10.1
python                     3.6
pyyaml                     3.12
matplotlib              3.1.3
pickleshare            0.7.5
torchvision            0.5.0
GPU                          GTX950M

**Comment by bamsumit** [comment]
Your GPU "GTX 950M" has cuda compute capability 5.0. The `setup.py` compiles the custom codes for cc 6.0 or higher. Please change the following line in `setup.py`
`'nvcc': ['-arch=sm_60', '-O2', '-use_fast_math']`
to
`'nvcc': ['-arch=sm_50', '-O2', '-use_fast_math']`
__Note:__ there are two such lines.
Let me know if that solves your problem.

**Comment by tyh97** [comment]
> Your GPU "GTX 950M" has cuda compute capability 5.0. The `setup.py` compiles the custom codes for cc 6.0 or higher. Please change the following line in `setup.py`
> `'nvcc': ['-arch=sm_60', '-O2', '-use_fast_math']`
> to
> `'nvcc': ['-arch=sm_50', '-O2', '-use_fast_math']`
> **Note:** there are two such lines.
> Let me know if that solves your problem.

That's OK！Thanks!
