### ISSUE TITLE
Slayer windows installation

### ISSUE THREAD

**Issue by giacomop96** [bamsumit/slayerPytorch#32]
I'm trying to install slayer on windows.
I have install cuda 10.1, cudnn, anaconda, pytorch.
When I run python setup.py install I get:
running install
running bdist_egg
running egg_info
writing slayerCuda.egg-info\PKG-INFO
writing dependency_links to slayerCuda.egg-info\dependency_links.txt
writing top-level names to slayerCuda.egg-info\top_level.txt
reading manifest file 'slayerCuda.egg-info\SOURCES.txt'
writing manifest file 'slayerCuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'slayerCuda' extension
Emitting ninja build file C:\Users\gpira\slayerPytorch\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /EHsc -IC:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include -IC:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\TH -IC:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\gpira\anaconda3\envs\pytorch\include -IC:\Users\gpira\anaconda3\envs\pytorch\include -c C:\Users\gpira\slayerPytorch\src\cuda\slayerKernels.cu -o C:\Users\gpira\slayerPytorch\build\temp.win-amd64-3.8\Release\src/cuda/slayerKernels.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -arch=sm_60 -O2 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=slayerCuda -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: C:/Users/gpira/slayerPytorch/build/temp.win-amd64-3.8/Release/src/cuda/slayerKernels.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /EHsc -IC:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include -IC:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\TH -IC:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\gpira\anaconda3\envs\pytorch\include -IC:\Users\gpira\anaconda3\envs\pytorch\include -c C:\Users\gpira\slayerPytorch\src\cuda\slayerKernels.cu -o C:\Users\gpira\slayerPytorch\build\temp.win-amd64-3.8\Release\src/cuda/slayerKernels.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -arch=sm_60 -O2 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=slayerCuda -D_GLIBCXX_USE_CXX11_ABI=0
c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\crt/host_config.h(236): fatal error C1083: Non Þ possibile aprire il file inclusione: 'crtdefs.h': No such file or directory
slayerKernels.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1418, in _run_ninja_build
    subprocess.run(
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 576, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1158, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

Those are a lot of errors and I'm no expert. Is there a way to solve this?

**Comment by bamsumit** [comment]
Try this [fix](https://github.com/bamsumit/slayerPytorch/issues/2#issuecomment-582315606) for windows.

**Comment by giacomop96** [comment]
Thanks for the tip. 
May I ask where I can find the header file to be modified?

**Comment by bamsumit** [comment]
Hi, it should appear in one of the compilation errors.

Alternatively, you may look at one of the following locations
```
C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include 
C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\TH 
C:\Users\gpira\anaconda3\envs\pytorch\lib\site-packages\torch\include\THC 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include 
C:\Users\gpira\anaconda3\envs\pytorch\include 
C:\Users\gpira\anaconda3\envs\pytorch\include
```

**Comment by giacomop96** [comment]
thanks I'll check immediately

**Comment by giacomop96** [comment]
Really I checked everywhere but I can't find them!! Don't know what to do..

**Comment by bamsumit** [comment]
`C:/Users/gpira/anaconda3/envs/slayerVenv/lib/site-packages/torch/include\torch/csrc/jit/argument_spec.h`
`C:/Users/gpira/anaconda3/envs/slayerVenv/lib/site-packages/torch/include\torch/csrc/jit/script/module.h`
However, your error seems different!
`c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\crt/host_config.h(236): fatal error C1083: Non Þ possibile aprire il file inclusione: 'crtdefs.h': No such file or directory`
Try fixing it first.
