### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by tehreemnaqvi** [bamsumit/slayerPytorch#35]
Hi,
I am installing SLAYER using Ubuntu 18.04.
By referring all the instructions ,I got an errors given below:

running install
running bdist_egg
running egg_info
writing slayerCuda.egg-info/PKG-INFO
writing dependency_links to slayerCuda.egg-info/dependency_links.txt
writing top-level names to slayerCuda.egg-info/top_level.txt
reading manifest file 'slayerCuda.egg-info/SOURCES.txt'
writing manifest file 'slayerCuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'slayerCuda' extension
Emitting ninja build file /home/tehreem/Desktop/slayerPytorch-master/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/bin/nvcc -I/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include -I/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/TH -I/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/THC -I/home/tehreem/anaconda3/envs/slayer_snn/include/python3.8 -c -c /home/tehreem/Desktop/slayerPytorch-master/src/cuda/slayerKernels.cu -o /home/tehreem/Desktop/slayerPytorch-master/build/temp.linux-x86_64-3.8/src/cuda/slayerKernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -arch=sm_60 -O2 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=slayerCuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/tehreem/Desktop/slayerPytorch-master/build/temp.linux-x86_64-3.8/src/cuda/slayerKernels.o 
/usr/bin/nvcc -I/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include -I/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/TH -I/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/THC -I/home/tehreem/anaconda3/envs/slayer_snn/include/python3.8 -c -c /home/tehreem/Desktop/slayerPytorch-master/src/cuda/slayerKernels.cu -o /home/tehreem/Desktop/slayerPytorch-master/build/temp.linux-x86_64-3.8/src/cuda/slayerKernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -arch=sm_60 -O2 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=slayerCuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/ATen/record_function.h(18): warning: attribute "__visibility__" does not apply here

/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/profiler.h(97): warning: attribute "__visibility__" does not apply here

/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/profiler.h(126): warning: attribute "__visibility__" does not apply here

/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/pybind11/cast.h(1449): error: invalid redeclaration of member function "pybind11::detail::copyable_holder_caster<type, holder_type>::operator type *()"
(1448): here

/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/enum.h(187): warning: statement is unreachable

1 error detected in the compilation of "/tmp/tmpxft_00002cc5_00000000-6_slayerKernels.cpp1.ii".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _run_ninja_build
    subprocess.run(
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 469, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1228, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/tehreem/anaconda3/envs/slayer_snn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

How to fix these errors? I tried a lot but couldn't install SLAYER.

Thanks

**Comment by bamsumit** [comment]
What are the output of the following commands:
`python -c "import torch; print(torch.__version__)"`
`nvcc --version`
`nvidia-smi | grep Version`

**Comment by tehreemnaqvi** [comment]
Pytorch version = 1.6.0
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2

**Comment by bamsumit** [comment]
nvcc --version ?

**Comment by tehreemnaqvi** [comment]
It's 10.2.

**Comment by tehreemnaqvi** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by bamsumit** [comment]
It is possible that it is due to torch version. We have it working properly up to torch version 1.4.0.

**Comment by tehreemnaqvi** [comment]
Then, I should check with PyTorch 1.4.0?

**Comment by bamsumit** [comment]
Yes

**Comment by tehreemnaqvi** [comment]
okay, Thank you very much.
