### ISSUE TITLE
unittest FAILED (failures=10, errors=1)

### ISSUE THREAD

**Issue by liumingchen1** [bamsumit/slayerPytorch#40]
gcc --version : 5.4.0
g++ --version : 5.4.0
nvcc --version : 10.0

Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
..F.FF......FF..F..F.E.FFF....
======================================================================
ERROR: test (test_slayer013.TestUnpooling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayer013.py", line 76, in test
    out   = unpool(inTensor)
  File "/home/mcliu/anaconda3/envs/my_slayer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mcliu/anaconda3/envs/my_slayer/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 736, in forward
    self.stride, self.padding, self.output_padding, self.groups, self.dilation,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

======================================================================
FAIL: testOut (test_slayer002.testSpike)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayer002.py", line 196, in testOut
    self.assertEqual(torch.norm(spikeGT - spikeOut), 0, 'Error mus be zero.')
AssertionError: tensor(157.8454, device='cuda:0', grad_fn=<NormBackward0>) != 0 : Error mus be zero.

======================================================================
FAIL: test (test_slayer003.testGradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayer003.py", line 100, in test
    self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
AssertionError: False is not true : Error must be close to zero.

======================================================================
FAIL: test (test_slayer004.testSpikeClassifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayer004.py", line 72, in test
    self.assertEqual(predict.getClass(spikeOut), 21, 'Correct class is 21.')
AssertionError: tensor([24]) != 21 : Correct class is 21.

======================================================================
FAIL: testShift (test_slayer009.TestDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayer009.py", line 81, in testShift
    self.assertEqual(netError, 0, 'Shift error must be zero.')
AssertionError: 667757.5945796967 != 0 : Shift error must be zero.

======================================================================
FAIL: testShiftPerNeuron (test_slayer009.TestDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayer009.py", line 63, in testShiftPerNeuron
    self.assertEqual(netError, 0, 'Shift (per neuron) error must be zero.')
AssertionError: 667407.997882843 != 0 : Shift (per neuron) error must be zero.

======================================================================
FAIL: test (test_slayer011.TestPspLayer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayer011.py", line 43, in test
    self.assertTrue(error < 1e-6, 'Result from Psp function and Psp layer must match.')
AssertionError: tensor(0, device='cuda:0', dtype=torch.uint8) is not true : Result from Psp function and Psp layer must match.

======================================================================
FAIL: testValues (test_slayer012.TestPspFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayer012.py", line 53, in testValues
    self.assertTrue(error < 1e-6, 'Result from Psp function and Psp filter bank must match.')
AssertionError: tensor(0, device='cuda:0', dtype=torch.uint8) is not true : Result from Psp function and Psp filter bank must match.

======================================================================
FAIL: testOutput (test_slayerLoihi001.testLoihiSpikes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayerLoihi001.py", line 123, in testOutput
    self.assertTrue(error<1e-3, 'Output spike and ground truth must match.')
AssertionError: False is not true : Output spike and ground truth must match.

======================================================================
FAIL: testHidden (test_slayerLoihi001.testLoihiVoltage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayerLoihi001.py", line 129, in testHidden
    self.assertTrue(error<1e-3, 'Hidden voltage and ground truth must match.')
AssertionError: False is not true : Hidden voltage and ground truth must match.

======================================================================
FAIL: testOutput (test_slayerLoihi001.testLoihiVoltage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcliu/program/slayerPytorch-master/test/test_slayerLoihi001.py", line 133, in testOutput
    self.assertTrue(error<1e-3, 'Hidden voltage and ground truth must match.')
AssertionError: False is not true : Hidden voltage and ground truth must match.

----------------------------------------------------------------------
Ran 30 tests in 45.314s

FAILED (failures=10, errors=1)

Thanks!

**Comment by bamsumit** [comment]
Can you post the following details
- GPU compute capability
- nvidia driver version
- cuda runtime version (that appears in `nvidia-smi`)

Also, can you confirm that you are able to compile and run any of the cuda samples?

**Comment by liumingchen1** [comment]
> Can you post the following details
> 
>     * GPU compute capability
> 
>     * nvidia driver version
> 
>     * cuda runtime version (that appears in `nvidia-smi`)
> 
> 
> Also, can you confirm that you are able to compile and run any of the cuda samples?

Ok, thinks! My gcc version is too low! I upgraded it to 7.5.0. 
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
And I successfully solved this problem, but a new problem appeared again:

======================================================================
ERROR: test (test_slayer013.TestUnpooling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu307_0/slayerPytorch-master/test/test_slayer013.py", line 76, in test
    out   = unpool(inTensor)
  File "/home/ubuntu307_0/anaconda3/envs/my_slayer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu307_0/anaconda3/envs/my_slayer/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 736, in forward
    self.stride, self.padding, self.output_padding, self.groups, self.dilation,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

----------------------------------------------------------------------
Ran 30 tests in 15.783s

FAILED (errors=1)


Could you help me solve it? Thank you!

**Comment by bamsumit** [comment]
You can ignore this error for now. This will be fixed in next commits.
