### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by asudeeaydin** [bamsumit/slayerPytorch#90]
Hi, I'm getting the following error when I run the unittest. 

```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
.....................E...........
======================================================================
ERROR: test (test_slayer013.TestUnpooling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asude/thesis/master_thesis_asude_aydin/DHP19/slayer/slayerPytorch/test/test_slayer013.py", line 76, in test
    out   = unpool(inTensor)
  File "/home/asude/slayer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asude/slayer/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 736, in forward
    self.stride, self.padding, self.output_padding, self.groups, self.dilation,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

----------------------------------------------------------------------
Ran 33 tests in 68.509s

FAILED (errors=1)
```

torch version: 1.1.0
Driver Version: 510.73.08    CUDA Version: 11.6 
nvcc version: 9.1
GCC version: 9.4

I'm not sure how to solve this problem, would really appreciate some help!

**Comment by bamsumit** [comment]
Hi did you successfully install the package?

**Comment by asudeeaydin** [comment]
Yes, as far as I can tell the installation process was successful

**Comment by bamsumit** [comment]
Can you try adding `.contiguous()` in line 734 and 740 of `slayer.py`
` input.reshape(...)`**`.contiguous()`**

**Comment by sleipnier** [comment]
> Can you try adding `.contiguous()` in line 734 and 740 of `slayer.py` ` input.reshape(...)`**`.contiguous()`**
I tried to add this code. But it did not work. The first 6 test_slayer show the error that "RuntimeError: Unable to find a valid cuDNN algorithm to run convolution". The rest of them show the error "RuntimeError: CUDA error: no kernel image is available for execution on the device" Hope someone could help to solve this problem
